package lib

import (
	"errors"

	"github.com/dcaiafa/nitro"
)

var (
	errNotEnoughArgs = errors.New("not enough arguments")
	errTooManyArgs   = errors.New("too many arguments")
	errTakesNoArgs   = errors.New("function does not take arguments")
)

func RegisterAll(c *nitro.Compiler) {
	c.AddNativeFn("avg", avg)
	c.AddNativeFn("buf", buf)
	c.AddNativeFn("close", closep)
	c.AddNativeFn("color", color)
	c.AddNativeFn("copyfile", copyfile)
	c.AddNativeFn("count", count)
	c.AddNativeFn("create", create)
	c.AddNativeFn("createtemp", createtemp)
	c.AddNativeFn("dur", dur)
	c.AddNativeFn("env", env)
	c.AddNativeFn("exec", exec)
	c.AddNativeFn("fileexists", fileexists)
	c.AddNativeFn("filter", filter)
	c.AddNativeFn("group", group)
	c.AddNativeFn("isdir", isdir)
	c.AddNativeFn("join", join)
	c.AddNativeFn("lines", lines)
	c.AddNativeFn("log", log)
	c.AddNativeFn("logf", logf)
	c.AddNativeFn("ls", ls)
	c.AddNativeFn("map", mapp)
	c.AddNativeFn("mapreduce", mapreduce)
	c.AddNativeFn("max", max)
	c.AddNativeFn("min", min)
	c.AddNativeFn("mkdirall", mkdirall)
	c.AddNativeFn("nonl", nonl)
	c.AddNativeFn("now", now)
	c.AddNativeFn("open", open)
	c.AddNativeFn("parsebase64", parsebase64)
	c.AddNativeFn("parsecsv", parsecsv)
	c.AddNativeFn("parsefloat", parsefloat)
	c.AddNativeFn("parseint", parseint)
	c.AddNativeFn("parsejson", parsejson)
	c.AddNativeFn("parsetime", parsetime)
	c.AddNativeFn("pathbase", pathbase)
	c.AddNativeFn("pathclean", pathclean)
	c.AddNativeFn("pathdir", pathdir)
	c.AddNativeFn("pathext", pathext)
	c.AddNativeFn("pathfromslash", pathfromslash)
	c.AddNativeFn("pathtoslash", pathtoslash)
	c.AddNativeFn("pathjoin", pathjoin)
	c.AddNativeFn("pathmatch", pathmatch)
	c.AddNativeFn("popstdout", popstdout)
	c.AddNativeFn("print", print)
	c.AddNativeFn("printf", printf)
	c.AddNativeFn("printtable", printtable)
	c.AddNativeFn("probe", probe)
	c.AddNativeFn("prompt", prompt)
	c.AddNativeFn("pushstdout", pushstdout)
	c.AddNativeFn("read", read)
	c.AddNativeFn("readfile", readfile)
	c.AddNativeFn("reduce", reduce)
	c.AddNativeFn("regex", regex)
	c.AddNativeFn("removeall", removeall)
	c.AddNativeFn("removefile", removefile)
	c.AddNativeFn("seek", seek)
	c.AddNativeFn("shuffle", shuffle)
	c.AddNativeFn("skip", skip)
	c.AddNativeFn("sleep", sleep)
	c.AddNativeFn("sort", sort)
	c.AddNativeFn("sprintf", sprintf)
	c.AddNativeFn("stat", stat)
	c.AddNativeFn("stderr", stderr)
	c.AddNativeFn("stdin", stdin)
	c.AddNativeFn("stdout", stdout)
	c.AddNativeFn("sum", sum)
	c.AddNativeFn("take", take)
	c.AddNativeFn("timefromunix", timefromunix)
	c.AddNativeFn("toarray", toarray)
	c.AddNativeFn("tobase64", tobase64)
	c.AddNativeFn("toint", toint)
	c.AddNativeFn("tojson", tojson)
	c.AddNativeFn("tomap", tomap)
	c.AddNativeFn("tostring", tostring)
	c.AddNativeFn("type", typep)
	c.AddNativeFn("unique", unique)
	c.AddNativeFn("userhomedir", userhomedir)
	c.AddNativeFn("utime", utime)
	c.AddNativeFn("writefile", writefile)
}
