// Code generated by goyacc parser.y. DO NOT EDIT.

//line parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser.y:2

import (
	"github.com/dcaiafa/nitro/internal/ast"
	"github.com/dcaiafa/nitro/internal/token"
)

//line parser.y:11
type yySymType struct {
	yys   int
	tok   token.Token
	ast   ast.AST
	asts  ast.ASTs
	expr  ast.Expr
	exprs ast.Exprs
	other interface{}
}

const LEXERR = 57346
const kAND = 57347
const kDO = 57348
const kELIF = 57349
const kELSE = 57350
const kEND = 57351
const kFALSE = 57352
const kFN = 57353
const kFOR = 57354
const kIF = 57355
const kIN = 57356
const kNOT = 57357
const kOR = 57358
const kRETURN = 57359
const kTHEN = 57360
const kTRUE = 57361
const kVAR = 57362
const kWHILE = 57363
const NUMBER = 57364
const STRING = 57365
const ID = 57366
const EQ = 57367
const NE = 57368
const LE = 57369
const GE = 57370

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEXERR",
	"kAND",
	"kDO",
	"kELIF",
	"kELSE",
	"kEND",
	"kFALSE",
	"kFN",
	"kFOR",
	"kIF",
	"kIN",
	"kNOT",
	"kOR",
	"kRETURN",
	"kTHEN",
	"kTRUE",
	"kVAR",
	"kWHILE",
	"NUMBER",
	"STRING",
	"ID",
	"'='",
	"EQ",
	"NE",
	"'<'",
	"LE",
	"'>'",
	"GE",
	"'\"'",
	"'|'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"';'",
	"'('",
	"','",
	"'['",
	"':'",
	"'.'",
	"'{'",
	"')'",
	"']'",
	"'}'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 93,
	26, 0,
	27, 0,
	28, 0,
	29, 0,
	30, 0,
	31, 0,
	-2, 43,
	-1, 94,
	26, 0,
	27, 0,
	28, 0,
	29, 0,
	30, 0,
	31, 0,
	-2, 44,
	-1, 95,
	26, 0,
	27, 0,
	28, 0,
	29, 0,
	30, 0,
	31, 0,
	-2, 45,
	-1, 96,
	26, 0,
	27, 0,
	28, 0,
	29, 0,
	30, 0,
	31, 0,
	-2, 46,
	-1, 97,
	26, 0,
	27, 0,
	28, 0,
	29, 0,
	30, 0,
	31, 0,
	-2, 47,
	-1, 98,
	26, 0,
	27, 0,
	28, 0,
	29, 0,
	30, 0,
	31, 0,
	-2, 48,
}

const yyPrivate = 57344

const yyLast = 658

var yyAct = [...]int{

	14, 3, 78, 70, 188, 182, 160, 80, 106, 54,
	72, 118, 124, 117, 162, 142, 137, 169, 56, 128,
	61, 62, 68, 147, 66, 148, 67, 127, 120, 126,
	119, 144, 138, 51, 156, 69, 73, 109, 105, 59,
	150, 88, 89, 90, 91, 92, 93, 94, 95, 96,
	97, 98, 99, 100, 49, 50, 45, 46, 47, 48,
	103, 58, 41, 42, 43, 44, 103, 111, 102, 115,
	49, 50, 45, 46, 47, 48, 59, 122, 41, 42,
	43, 44, 101, 129, 43, 44, 130, 123, 86, 85,
	87, 125, 164, 39, 103, 108, 131, 134, 55, 112,
	81, 53, 132, 133, 216, 213, 135, 212, 209, 195,
	139, 192, 140, 21, 136, 191, 179, 82, 165, 204,
	73, 73, 41, 42, 43, 44, 198, 175, 189, 153,
	145, 146, 183, 161, 151, 152, 63, 64, 65, 163,
	121, 5, 143, 1, 197, 166, 37, 196, 181, 180,
	73, 168, 75, 167, 74, 71, 31, 171, 170, 172,
	203, 202, 177, 187, 178, 186, 176, 84, 83, 79,
	185, 32, 114, 113, 107, 33, 25, 193, 8, 7,
	9, 174, 173, 159, 200, 73, 158, 199, 201, 10,
	206, 11, 205, 207, 60, 12, 208, 13, 4, 73,
	2, 0, 210, 0, 0, 0, 0, 214, 0, 0,
	0, 0, 73, 0, 0, 217, 0, 0, 218, 30,
	18, 16, 17, 0, 22, 0, 19, 0, 29, 15,
	20, 27, 26, 28, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 23, 24, 0, 0, 6, 34, 0,
	35, 0, 0, 36, 30, 18, 16, 17, 0, 22,
	0, 19, 0, 29, 15, 20, 27, 26, 28, 51,
	0, 0, 0, 0, 0, 0, 0, 0, 23, 24,
	52, 0, 38, 34, 0, 35, 0, 0, 36, 0,
	49, 50, 45, 46, 47, 48, 51, 0, 41, 42,
	43, 44, 0, 0, 0, 0, 0, 52, 0, 0,
	154, 0, 0, 0, 0, 0, 0, 49, 50, 45,
	46, 47, 48, 0, 0, 41, 42, 43, 44, 30,
	57, 77, 76, 0, 22, 0, 0, 141, 29, 0,
	0, 27, 26, 28, 51, 0, 0, 0, 0, 0,
	0, 0, 0, 23, 24, 52, 0, 0, 34, 0,
	35, 0, 0, 36, 0, 49, 50, 45, 46, 47,
	48, 0, 0, 41, 42, 43, 44, 30, 57, 0,
	0, 0, 22, 0, 116, 0, 29, 0, 0, 27,
	26, 28, 51, 0, 0, 0, 0, 0, 0, 0,
	0, 23, 24, 52, 0, 215, 34, 0, 35, 0,
	0, 36, 0, 49, 50, 45, 46, 47, 48, 51,
	0, 41, 42, 43, 44, 0, 0, 0, 0, 0,
	52, 0, 211, 0, 0, 0, 0, 0, 0, 0,
	49, 50, 45, 46, 47, 48, 51, 0, 41, 42,
	43, 44, 0, 0, 0, 0, 0, 52, 0, 194,
	0, 0, 51, 190, 0, 0, 0, 49, 50, 45,
	46, 47, 48, 52, 0, 41, 42, 43, 44, 51,
	184, 0, 0, 49, 50, 45, 46, 47, 48, 0,
	52, 41, 42, 43, 44, 51, 157, 0, 0, 0,
	49, 50, 45, 46, 47, 48, 52, 0, 41, 42,
	43, 44, 0, 0, 0, 0, 49, 50, 45, 46,
	47, 48, 51, 0, 41, 42, 43, 44, 0, 0,
	0, 0, 0, 52, 0, 155, 0, 0, 0, 0,
	0, 0, 0, 49, 50, 45, 46, 47, 48, 51,
	0, 41, 42, 43, 44, 0, 0, 0, 0, 0,
	52, 0, 149, 0, 0, 51, 110, 0, 0, 0,
	49, 50, 45, 46, 47, 48, 52, 0, 41, 42,
	43, 44, 0, 0, 0, 0, 49, 50, 45, 46,
	47, 48, 51, 0, 41, 42, 43, 44, 0, 0,
	0, 0, 0, 52, 0, 104, 0, 0, 51, 0,
	0, 0, 0, 49, 50, 45, 46, 47, 48, 52,
	0, 41, 42, 43, 44, 51, 0, 0, 40, 49,
	50, 45, 46, 47, 48, 0, 52, 41, 42, 43,
	44, 0, 0, 0, 0, 0, 49, 50, 45, 46,
	47, 48, 0, 0, 41, 42, 43, 44,
}
var yyPact = [...]int{

	209, -1000, -1000, -1000, 244, 55, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 603, 77, 74, 367, 37, 367,
	367, -1000, 367, 367, 367, -17, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 367, 319, 76, 52, -1000, -1000,
	367, 367, 367, 367, 367, 367, 367, 367, 367, 367,
	367, 367, 367, 57, 54, -1000, 587, 0, -1, 71,
	-3, 620, 560, -1000, -1000, -1000, 367, 75, 367, 339,
	-33, -10, -1000, 620, -1000, -1000, 367, 74, -35, -11,
	-1000, -23, 367, -1000, -1000, 367, 74, -1000, 620, 48,
	48, -1000, -1000, 88, 88, 88, 88, 88, 88, 44,
	28, 367, 367, 73, 209, 71, -29, -8, -1000, 367,
	209, 291, -1000, -30, -9, 620, -1000, -1000, -1000, 319,
	319, -15, 544, 26, -1000, -1000, 76, 76, 367, 264,
	517, 20, 620, 490, -1000, 126, -31, 209, 68, 620,
	109, -1000, -1000, -1000, 367, -1000, -1000, -1000, -1000, 319,
	367, -1000, -1000, 620, -25, 76, 367, 209, 119, 126,
	-1000, 367, 209, 107, -1000, -1000, 620, 125, 474, 367,
	121, 457, 106, 102, -1000, 209, -1000, 441, 100, -1000,
	118, 125, -1000, 367, 319, 620, 111, 121, -1000, 367,
	76, -1000, -1000, -1000, 209, -1000, 99, -1000, 319, -1000,
	414, 98, 96, -1000, 76, -1000, 387, 95, -1000, -1000,
	-1000, 319, -1000, -1000, -1000, 76, -1000, -1000, -1000,
}
var yyPgo = [...]int{

	0, 200, 1, 198, 141, 197, 195, 194, 191, 189,
	186, 183, 6, 182, 181, 180, 9, 179, 178, 0,
	113, 176, 175, 8, 174, 173, 172, 171, 2, 169,
	7, 168, 167, 165, 163, 4, 161, 160, 156, 3,
	155, 10, 154, 152, 149, 148, 5, 147, 144, 143,
	142, 11, 140,
}
var yyR1 = [...]int{

	0, 49, 1, 2, 2, 2, 3, 3, 3, 3,
	4, 4, 4, 4, 4, 4, 4, 4, 5, 6,
	7, 7, 8, 9, 10, 10, 11, 11, 12, 13,
	13, 14, 15, 16, 16, 17, 18, 18, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 20, 20, 20, 20, 21, 21, 21, 21, 21,
	21, 21, 21, 21, 21, 21, 21, 22, 23, 23,
	24, 24, 25, 25, 26, 26, 27, 28, 28, 29,
	29, 29, 30, 30, 30, 30, 31, 32, 33, 33,
	34, 34, 35, 36, 36, 37, 38, 39, 39, 40,
	40, 40, 41, 41, 41, 42, 43, 44, 44, 45,
	45, 46, 47, 47, 48, 51, 51, 52, 52, 52,
	52, 50, 50,
}
var yyR2 = [...]int{

	0, 1, 1, 1, 1, 0, 3, 2, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 5, 2,
	3, 1, 7, 7, 1, 0, 2, 1, 4, 1,
	0, 2, 7, 3, 1, 3, 2, 4, 1, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 2, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 4, 3, 4, 1, 3, 6, 1, 0,
	3, 1, 2, 0, 3, 1, 3, 2, 0, 3,
	3, 1, 3, 5, 1, 1, 7, 7, 1, 0,
	2, 1, 4, 1, 0, 2, 3, 2, 0, 3,
	3, 1, 1, 1, 1, 7, 7, 1, 0, 2,
	1, 4, 1, 0, 2, 0, 1, 2, 2, 1,
	1, 1, 0,
}
var yyChk = [...]int{

	-1000, -49, -1, -2, -3, -4, 38, -17, -18, -15,
	-9, -8, -6, -5, -19, 20, 12, 13, 11, 17,
	21, -20, 15, 34, 35, -21, 23, 22, 24, 19,
	10, -38, -27, -22, 39, 41, 44, -4, 38, 38,
	25, 34, 35, 36, 37, 28, 29, 30, 31, 26,
	27, 5, 16, 24, -16, 24, -19, 11, 24, 39,
	-7, -19, -19, -20, -20, -20, 41, 43, 39, -19,
	-39, -40, -41, -19, -42, -43, 13, 12, -28, -29,
	-30, 24, 41, -31, -32, 13, 12, 38, -19, -19,
	-19, -19, -19, -19, -19, -19, -19, -19, -19, -19,
	-19, 25, 14, 40, 18, 39, -23, -24, 24, 40,
	6, -19, 24, -25, -26, -19, 45, 46, -51, 40,
	38, -52, -19, -16, 47, -51, 40, 38, 42, -19,
	-19, -16, -19, -19, 24, -2, -23, 45, 40, -19,
	-2, 46, 45, -50, 40, -41, -41, 38, 40, 18,
	14, -30, -30, -19, 46, 18, 14, 6, -10, -11,
	-12, 7, 45, -2, 24, 9, -19, -39, -19, 42,
	-28, -19, -2, -13, -14, 8, -12, -19, -2, 9,
	-44, -45, -46, 7, 6, -19, -33, -34, -35, 7,
	6, 9, 9, -2, 18, 9, -47, -48, 8, -46,
	-19, -39, -36, -37, 8, -35, -19, -28, -2, 9,
	-39, 18, 9, 9, -28, 18, 9, -39, -28,
}
var yyDef = [...]int{

	5, -2, 1, 2, 3, 4, 9, 10, 11, 12,
	13, 14, 15, 16, 17, 0, 0, 0, 0, 0,
	0, 38, 0, 0, 0, 54, 55, 56, 57, 58,
	59, 60, 61, 65, 0, 98, 78, 0, 7, 8,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 36, 0, 34, 0, 0, 0, 69,
	19, 21, 0, 51, 52, 53, 0, 0, 73, 0,
	0, 115, 101, 102, 103, 104, 0, 0, 0, 115,
	81, 0, 0, 84, 85, 0, 0, 6, 35, 39,
	40, 41, 42, -2, -2, -2, -2, -2, -2, 49,
	50, 0, 0, 0, 5, 69, 0, 68, 71, 0,
	5, 0, 63, 0, 122, 75, 66, 96, 97, 120,
	119, 116, 0, 0, 76, 77, 120, 119, 0, 0,
	0, 0, 37, 0, 33, 25, 0, 5, 0, 20,
	0, 62, 64, 72, 121, 99, 100, 117, 118, 98,
	0, 79, 80, 82, 0, 78, 0, 5, 30, 24,
	27, 0, 5, 0, 70, 18, 74, 108, 0, 0,
	89, 0, 0, 0, 29, 5, 26, 0, 0, 67,
	113, 107, 110, 0, 98, 83, 94, 88, 91, 0,
	78, 32, 23, 31, 5, 22, 0, 112, 98, 109,
	0, 0, 0, 93, 78, 90, 0, 0, 28, 105,
	114, 98, 106, 86, 95, 78, 87, 111, 92,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 32, 3, 3, 3, 3, 3,
	39, 45, 36, 34, 40, 35, 43, 37, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 42, 38,
	28, 25, 30, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 41, 3, 46, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 44, 33, 47,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 26, 27, 29, 31,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:106
		{
			yylex.(*lex).Program = yyDollar[1].ast.(*ast.Program)
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:108
		{
			yyVAL.ast = &ast.Program{Stmts: yyDollar[1].asts}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:111
		{
			yyVAL.asts = ast.ASTs{yyDollar[1].ast}
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:112
		{
			yyVAL.asts = ast.ASTs{}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:114
		{
			l := yyDollar[1].asts
			yyVAL.asts = append(l, yyDollar[2].ast)
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:116
		{
			yyVAL.asts = ast.ASTs{yyDollar[1].ast}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:117
		{
			yyVAL.asts = ast.ASTs{}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:126
		{
			yyVAL.ast = &ast.ExprStmt{Expr: yyDollar[1].expr}
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:131
		{
			yyVAL.ast = &ast.WhileStmt{Predicate: yyDollar[2].expr, Stmts: yyDollar[4].asts}
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:133
		{
			yyVAL.ast = &ast.ReturnStmt{Values: yyDollar[2].ast.(ast.Exprs)}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:135
		{
			e := yyDollar[1].ast.(ast.Exprs)
			e = append(e, yyDollar[3].expr)
			yyVAL.ast = e
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:136
		{
			yyVAL.ast = ast.Exprs{yyDollar[1].expr}
		}
	case 22:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:141
		{
			fn := &ast.LambdaExpr{FuncParams: yyDollar[4].asts, Stmts: yyDollar[6].asts}
			yyVAL.ast = &ast.VarDeclStmt{VarName: yyDollar[2].tok, InitValue: fn}
		}
	case 23:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:151
		{
			ifBlock := &ast.IfBlock{Pred: yyDollar[2].expr, Stmts: yyDollar[4].asts}
			ifStmt := &ast.IfStmt{Blocks: ast.ASTs{ifBlock}}
			if yyDollar[5].asts != nil {
				ifStmt.Blocks = append(ifStmt.Blocks, yyDollar[5].asts...)
			}
			if yyDollar[6].ast != nil {
				ifStmt.Blocks = append(ifStmt.Blocks, yyDollar[6].ast)
			}
			yyVAL.ast = ifBlock
		}
	case 25:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:164
		{
			yyVAL.asts = ast.ASTs{}
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:166
		{
			l := yyDollar[1].asts
			yyVAL.asts = append(l, yyDollar[2].ast)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:167
		{
			yyVAL.asts = ast.ASTs{yyDollar[1].ast}
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:171
		{
			yyVAL.ast = &ast.IfBlock{Pred: yyDollar[2].expr, Stmts: yyDollar[4].asts}
		}
	case 30:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:174
		{
			yyVAL.ast = nil
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:178
		{
			yyVAL.ast = &ast.IfBlock{Pred: nil, Stmts: yyDollar[2].asts}
		}
	case 32:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:183
		{
			yyVAL.ast = &ast.ForStmt{ForVars: yyDollar[2].asts, IterExpr: yyDollar[4].expr, Stmts: yyDollar[6].asts}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:185
		{
			l := yyDollar[1].asts
			yyVAL.asts = append(l, &ast.ForVar{VarName: yyDollar[3].tok})
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:186
		{
			yyVAL.asts = ast.ASTs{&ast.ForVar{VarName: yyDollar[1].tok}}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:188
		{
			yyVAL.ast = &ast.AssignStmt{Lvalue: yyDollar[1].expr, Rvalue: yyDollar[3].expr}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:190
		{
			yyVAL.ast = &ast.VarDeclStmt{VarName: yyDollar[2].tok, InitValue: nil}
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:191
		{
			yyVAL.ast = &ast.VarDeclStmt{VarName: yyDollar[2].tok, InitValue: yyDollar[4].expr}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:194
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpPlus}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:195
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpMinus}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:196
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpMult}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:197
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpDiv}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:198
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpLT}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:199
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpLE}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:200
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpGT}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:201
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpGE}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:202
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpEq}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:203
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpNE}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:204
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpAnd}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:205
		{
			yyVAL.expr = &ast.BinaryExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr, Op: ast.OpOr}
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:207
		{
			yyVAL.expr = &ast.UnaryExpr{Term: yyDollar[2].expr, Op: ast.OpNot}
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:208
		{
			yyVAL.expr = &ast.UnaryExpr{Term: yyDollar[2].expr, Op: ast.OpPlus}
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:209
		{
			yyVAL.expr = &ast.UnaryExpr{Term: yyDollar[2].expr, Op: ast.OpMinus}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:212
		{
			yyVAL.expr = &ast.LiteralExpr{Val: yyDollar[1].tok}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:213
		{
			yyVAL.expr = &ast.LiteralExpr{Val: yyDollar[1].tok}
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:214
		{
			yyVAL.expr = &ast.SimpleRef{ID: yyDollar[1].tok}
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:215
		{
			yyVAL.expr = &ast.LiteralExpr{Val: yyDollar[1].tok}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:216
		{
			yyVAL.expr = &ast.LiteralExpr{Val: yyDollar[1].tok}
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:219
		{
			yyVAL.expr = &ast.IndexExpr{Target: yyDollar[1].expr, Index: yyDollar[3].expr}
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:220
		{
			yyVAL.expr = &ast.MemberAccess{Target: yyDollar[1].expr, Member: yyDollar[3].tok}
		}
	case 64:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:221
		{
			yyVAL.expr = &ast.FuncCall{Target: yyDollar[1].expr, Args: yyDollar[3].exprs}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:223
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 67:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:228
		{
			yyVAL.expr = &ast.LambdaExpr{FuncParams: yyDollar[3].asts, Stmts: yyDollar[5].asts}
		}
	case 69:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:231
		{
			yyVAL.asts = ast.ASTs{}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:233
		{
			p := yyDollar[1].asts
			p = append(p, yyDollar[1].asts)
			yyVAL.asts = p
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:234
		{
			yyVAL.asts = ast.ASTs{&ast.FuncParam{Name: yyDollar[1].tok}}
		}
	case 73:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:237
		{
			yyVAL.exprs = ast.Exprs{}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:239
		{
			l := yyDollar[1].exprs
			yyVAL.exprs = append(l, yyDollar[3].expr)
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:240
		{
			yyVAL.exprs = ast.Exprs{yyDollar[1].expr}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:242
		{
			yyVAL.expr = &ast.ObjectLiteral{Fields: yyDollar[2].asts}
		}
	case 78:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:245
		{
			yyVAL.asts = ast.ASTs{}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:247
		{
			l := yyDollar[1].asts
			yyVAL.asts = append(l, yyDollar[3].ast)
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:248
		{
			l := yyDollar[1].asts
			yyVAL.asts = append(l, yyDollar[3].ast)
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:249
		{
			yyVAL.asts = ast.ASTs{yyDollar[1].ast}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:251
		{
			yyVAL.ast = &ast.ObjectField{NameID: yyDollar[1].tok, Val: yyDollar[3].expr}
		}
	case 83:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:252
		{
			yyVAL.ast = &ast.ObjectField{NameExpr: yyDollar[2].expr, Val: yyDollar[5].expr}
		}
	case 86:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:261
		{
			ifBlock := &ast.IfBlock{Pred: yyDollar[2].expr, Stmts: yyDollar[4].asts}
			ifStmt := &ast.IfStmt{Blocks: ast.ASTs{ifBlock}}
			if yyDollar[5].ast != nil {
				ifStmt.Blocks = append(ifStmt.Blocks, yyDollar[5].ast.(ast.ASTs)...)
			}
			if yyDollar[6].ast != nil {
				ifStmt.Blocks = append(ifStmt.Blocks, yyDollar[6].ast)
			}
			yyVAL.ast = ifStmt
		}
	case 87:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:276
		{
			yyVAL.ast = &ast.ForStmt{ForVars: yyDollar[2].asts, IterExpr: yyDollar[4].expr, Stmts: yyDollar[6].asts}
		}
	case 89:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:279
		{
			yyVAL.ast = ast.ASTs{}
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:281
		{
			l := yyDollar[1].ast.(ast.ASTs)
			yyVAL.ast = append(l, yyDollar[2].ast)
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:282
		{
			yyVAL.ast = ast.ASTs{yyDollar[1].ast}
		}
	case 92:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:286
		{
			yyVAL.ast = &ast.IfBlock{Pred: yyDollar[2].expr, Stmts: yyDollar[4].asts}
		}
	case 94:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:289
		{
			yyVAL.ast = nil
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:293
		{
			yyVAL.ast = &ast.IfBlock{Pred: nil, Stmts: yyDollar[2].asts}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:295
		{
			yyVAL.expr = &ast.ArrayLiteral{Elements: yyDollar[2].asts}
		}
	case 98:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:298
		{
			yyVAL.asts = ast.ASTs{}
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:300
		{
			l := yyDollar[1].asts
			yyVAL.asts = append(l, yyDollar[3].ast)
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:301
		{
			l := yyDollar[1].asts
			yyVAL.asts = append(l, yyDollar[3].ast)
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:302
		{
			yyVAL.asts = ast.ASTs{yyDollar[1].ast}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:304
		{
			yyVAL.ast = &ast.ArrayElement{Val: yyDollar[1].expr}
		}
	case 105:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:313
		{
			ifBlock := &ast.IfBlock{Pred: yyDollar[2].expr, Stmts: yyDollar[4].asts}
			ifStmt := &ast.IfStmt{Blocks: ast.ASTs{ifBlock}}
			if yyDollar[5].asts != nil {
				ifStmt.Blocks = append(ifStmt.Blocks, yyDollar[5].asts...)
			}
			if yyDollar[6].ast != nil {
				ifStmt.Blocks = append(ifStmt.Blocks, yyDollar[6].ast)
			}
			yyVAL.ast = ifStmt
		}
	case 106:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:328
		{
			yyVAL.ast = &ast.ForStmt{ForVars: yyDollar[2].asts, IterExpr: yyDollar[4].expr, Stmts: yyDollar[6].asts}
		}
	case 108:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:331
		{
			yyVAL.asts = ast.ASTs{}
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:333
		{
			l := yyDollar[1].asts
			yyVAL.asts = append(l, yyDollar[2].ast)
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:334
		{
			yyVAL.asts = ast.ASTs{yyDollar[1].ast}
		}
	case 111:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:338
		{
			yyVAL.ast = &ast.IfBlock{Pred: yyDollar[2].expr, Stmts: yyDollar[4].asts}
		}
	case 113:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:341
		{
			yyVAL.ast = nil
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:345
		{
			yyVAL.ast = &ast.IfBlock{Pred: nil, Stmts: yyDollar[2].asts}
		}
	}
	goto yystack /* stack new state and value */
}
