// Code generated by goyacc parser.y. DO NOT EDIT.

//line parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser.y:2

import ()

//line parser.y:9
type yySymType struct {
	yys  int
	num  float64
	str  string
	ast  interface{}
	expr interface{}
}

const LEXERR = 57346
const ID = 57347
const kTRUE = 57348
const kFALSE = 57349
const kIN = 57350
const kAND = 57351
const kOR = 57352
const kNOT = 57353
const kIF = 57354
const kELIF = 57355
const kELSE = 57356
const kEND = 57357
const kTHEN = 57358
const BLOCK_OPEN = 57359
const BLOCK_CLOSE = 57360
const NUMBER = 57361
const STRING = 57362
const OR = 57363
const AND = 57364
const LE = 57365
const GE = 57366
const EQ = 57367
const NE = 57368

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEXERR",
	"ID",
	"kTRUE",
	"kFALSE",
	"kIN",
	"kAND",
	"kOR",
	"kNOT",
	"kIF",
	"kELIF",
	"kELSE",
	"kEND",
	"kTHEN",
	"BLOCK_OPEN",
	"BLOCK_CLOSE",
	"NUMBER",
	"STRING",
	"OR",
	"AND",
	"'<'",
	"LE",
	"'>'",
	"GE",
	"EQ",
	"NE",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"','",
	"';'",
	"'='",
	"'.'",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"':'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 7,
	36, 22,
	-2, 10,
}

const yyPrivate = 57344

const yyLast = 114

var yyAct = [...]int{

	27, 21, 58, 43, 41, 24, 11, 33, 11, 25,
	8, 3, 8, 2, 18, 38, 39, 34, 26, 7,
	20, 7, 36, 19, 46, 67, 38, 39, 65, 40,
	54, 38, 39, 35, 44, 51, 62, 30, 38, 39,
	48, 49, 59, 11, 32, 50, 29, 8, 38, 39,
	45, 47, 55, 11, 53, 12, 7, 8, 12, 18,
	63, 64, 9, 66, 23, 52, 7, 1, 68, 17,
	14, 12, 17, 14, 22, 42, 13, 57, 9, 12,
	16, 56, 61, 16, 37, 17, 14, 15, 60, 10,
	15, 31, 10, 17, 14, 28, 16, 38, 39, 4,
	5, 6, 0, 15, 16, 10, 0, 0, 0, 0,
	0, 15, 0, 10,
}
var yyPact = [...]int{

	66, -1000, 66, -1000, -1000, -11, -1000, -1000, -15, 53,
	32, -29, -1000, -1000, -1000, 53, 14, -1000, -1000, -1000,
	53, 68, -1000, 74, -29, -1000, -1000, -36, 32, -1000,
	-38, -1000, 53, 45, -14, -1000, 2, 66, 53, 53,
	-29, -1000, -1000, 53, 19, -1000, -1000, 50, -1000, -1000,
	-3, 32, -1000, -1000, -1000, 29, 22, 29, -1000, 53,
	13, -1000, 32, -1000, 9, -1000, -1000, 32, -1000,
}
var yyPgo = [...]int{

	0, 101, 100, 99, 46, 95, 91, 88, 82, 0,
	81, 77, 2, 11, 13, 1, 76, 18, 9, 5,
	74, 67, 54,
}
var yyR1 = [...]int{

	0, 21, 14, 14, 22, 22, 13, 13, 13, 1,
	3, 2, 15, 15, 15, 18, 18, 20, 20, 19,
	19, 19, 19, 19, 16, 16, 17, 9, 9, 5,
	5, 4, 4, 6, 10, 10, 11, 11, 12, 7,
	7, 8,
}
var yyR2 = [...]int{

	0, 1, 2, 1, 1, 0, 1, 2, 1, 5,
	1, 3, 1, 3, 3, 3, 1, 2, 1, 1,
	1, 1, 1, 3, 2, 1, 3, 1, 0, 2,
	1, 4, 1, 7, 1, 0, 2, 1, 4, 1,
	0, 2,
}
var yyChk = [...]int{

	-1000, -21, -14, -13, -3, -2, -1, -17, -18, 12,
	39, -19, 5, -16, 20, 37, 30, 19, -13, 34,
	35, -15, -20, 11, -19, -18, -17, -9, -5, -4,
	5, -6, 12, 36, -15, 19, -15, 16, 29, 30,
	-19, 40, -4, 41, -15, 5, 38, -14, -15, -15,
	-15, 16, 15, -22, 33, -9, -10, -11, -12, 13,
	-7, -8, 14, -12, -15, 15, -9, 16, -9,
}
var yyDef = [...]int{

	0, -2, 1, 3, 6, 0, 8, -2, 21, 0,
	28, 0, 16, 19, 20, 0, 0, 25, 2, 7,
	0, 0, 12, 0, 18, 21, 22, 0, 27, 30,
	0, 32, 0, 0, 0, 24, 11, 0, 0, 0,
	17, 26, 29, 0, 0, 15, 23, 0, 13, 14,
	5, 28, 9, 31, 4, 35, 40, 34, 37, 0,
	0, 39, 28, 36, 0, 33, 41, 28, 38,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	37, 38, 31, 29, 33, 30, 36, 32, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 41, 34,
	23, 35, 25, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 39, 3, 40,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 24, 26, 27, 28,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:55
		{
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:57
		{
			yyVAL.ast = nil
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:58
		{
			yyVAL.ast = nil
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:63
		{
			yyVAL.ast = nil
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:64
		{
			yyVAL.ast = nil
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:65
		{
			yyVAL.ast = nil
		}
	case 9:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:70
		{
			yyVAL.ast = nil
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:72
		{
			yyVAL.ast = nil
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:74
		{
			yyVAL.ast = nil
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:76
		{
			yyVAL.expr = nil
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:77
		{
			yyVAL.expr = nil
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:78
		{
			yyVAL.expr = nil
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:80
		{
			yyVAL.expr = nil
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:81
		{
			yyVAL.expr = nil
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:83
		{
			yyVAL.expr = nil
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:84
		{
			yyVAL.expr = nil
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:86
		{
			yyVAL.expr = nil
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:87
		{
			yyVAL.expr = nil
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:88
		{
			yyVAL.expr = nil
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:89
		{
			yyVAL.expr = nil
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:90
		{
			yyVAL.expr = nil
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:92
		{
			yyVAL.expr = nil
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:93
		{
			yyVAL.expr = nil
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:95
		{
			yyVAL.expr = nil
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:97
		{
			yyVAL.ast = nil
		}
	case 28:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:98
		{
			yyVAL.ast = nil
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:100
		{
			yyVAL.ast = nil
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:101
		{
			yyVAL.ast = nil
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:103
		{
			yyVAL.ast = nil
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:104
		{
			yyVAL.ast = nil
		}
	case 33:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:111
		{
			yyVAL.ast = nil
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:113
		{
			yyVAL.ast = nil
		}
	case 35:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:114
		{
			yyVAL.ast = nil
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:116
		{
			yyVAL.ast = nil
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:117
		{
			yyVAL.ast = nil
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:121
		{
			yyVAL.ast = nil
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:123
		{
			yyVAL.ast = nil
		}
	case 40:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:124
		{
			yyVAL.ast = nil
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:128
		{
			yyVAL.ast = nil
		}
	}
	goto yystack /* stack new state and value */
}
